spring.data.mongodb.uri=mongodb+srv://taskmanager:taskmanager123@cluster0.ekshmgi.mongodb.net/taskmanager?retryWrites=true&w=majority&appName=Cluster0

jwt.secret=taskmanager_super_secret_key_2024_must_be_at_least_256_bits_long
jwt.expiration=86400000

server.port=8081
